# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-06 23:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aec', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.TextField(help_text='A person name at their first election', max_length=512, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='person',
            name='notes',
            field=models.CharField(blank=True, help_text="A one-line account of a person's life", max_length=1024, verbose_name='notes'),
        ),
    ]
