USE python:3.6

# See: https://docs.djangoproject.com/en/1.11/ref/contrib/gis/install/geolibs/
RUN sudo apt-get update
RUN sudo apt-get install binutils libproj-dev gdal-bin
RUN sudo apt-get install libgdal-dev

RUN pip install pygdal #NB: Slow
RUN pip install gdal

CMD waitress-serve