# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-08 00:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlternateName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(help_text='An alternate or former name', verbose_name='name')),
            ],
        ),
        migrations.CreateModel(
            name='Election',
            fields=[
                ('id', models.CharField(max_length=256, primary_key=True, serialize=False)),
                ('label', models.CharField(help_text='The name of the election', max_length=128)),
                ('type', models.CharField(blank=True, help_text='The type of election, eg. Full election, By-election, Casual vacancy', max_length=128)),
                ('poll_date', models.DateField(help_text='The date an election was held.')),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ElectoralRegion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='FirstPreferenceVotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_type', models.CharField(default='Ordinary', max_length=512)),
                ('votes', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Party',
            fields=[
                ('name', models.CharField(help_text='A primary name, e.g. a legally recognized name', max_length=512, verbose_name='name')),
                ('summary', models.CharField(blank=True, help_text='A one-line description of an organization', max_length=1024, verbose_name='summary')),
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name_plural': 'Parties',
            },
        ),
        migrations.CreateModel(
            name='PartyMembership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_start', models.DateField(blank=True, help_text='An uncertain date', null=True)),
                ('date_of_start_confidence', models.CharField(default='YYYY-MM-DD', help_text="The confidence of an uncertain date. Use 'YYYY','YYYY-MM' or 'YYYY-MM-DD'", max_length=200, null=True)),
                ('date_of_end', models.DateField(blank=True, help_text='An uncertain date', null=True)),
                ('date_of_end_confidence', models.CharField(default='YYYY-MM-DD', help_text="The confidence of an uncertain date. Use 'YYYY','YYYY-MM' or 'YYYY-MM-DD'", max_length=200, null=True)),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aec.Party')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(help_text='A person name at their first election', max_length=512, verbose_name='name')),
                ('country_of_birth', models.CharField(blank=True, help_text='Where they were born', max_length=256, verbose_name='Country of birth')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Unknown', 'Unknown'), ('Other', 'Other')], default='Male', max_length=20)),
                ('date_of_birth', models.DateField(blank=True, help_text='A date of birth', null=True)),
                ('date_of_birth_confidence', models.CharField(default='YYYY-MM-DD', help_text="The confidence of a date of birth. Use 'YYYY','YYYY-MM' or 'YYYY-MM-DD'", max_length=200, null=True)),
                ('date_of_death', models.DateField(blank=True, help_text='A date of death', null=True)),
                ('date_of_death_confidence', models.CharField(default='YYYY-MM-DD', help_text="The confidence of a date of death. Use 'YYYY','YYYY-MM' or 'YYYY-MM-DD'", max_length=200, null=True)),
                ('notes', models.CharField(blank=True, help_text="A one-line account of a person's life", max_length=1024, verbose_name='notes')),
            ],
            options={
                'verbose_name_plural': 'People',
            },
        ),
        migrations.CreateModel(
            name='PreferencesFlow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('votes', models.PositiveIntegerField(default=0, help_text='The total number of votes for an individual at a particular stage of counts')),
                ('stage_of_counts', models.PositiveIntegerField(default=0, help_text='The stage at which these counts are held. Stages start at 0, and the count increments when the lowest unsuccessful candidate is illiminated and their votes redistributed.')),
                ('person', models.ForeignKey(help_text='The person associated with a preferences result.', on_delete=django.db.models.deletion.CASCADE, to='aec.Person')),
            ],
            options={
                'ordering': ['stage_of_counts', '-votes'],
            },
        ),
        migrations.CreateModel(
            name='VoterRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Unknown', 'Unknown'), ('Other', 'Other')], default='Male', max_length=20)),
                ('enrolments', models.PositiveIntegerField(default=0)),
                ('votes_issued', models.PositiveIntegerField(default=0)),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aec.Election')),
            ],
        ),
        migrations.CreateModel(
            name='AustralianState',
            fields=[
                ('electoralregion_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='aec.ElectoralRegion')),
                ('abbreviation', models.CharField(max_length=1024)),
            ],
            bases=('aec.electoralregion',),
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('electoralregion_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='aec.ElectoralRegion')),
                ('state', models.CharField(max_length=1024)),
            ],
            bases=('aec.electoralregion',),
        ),
        migrations.CreateModel(
            name='Subdivision',
            fields=[
                ('electoralregion_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='aec.ElectoralRegion')),
                ('level', models.CharField(max_length=256)),
                ('parent_division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subdivisions', to='aec.Division')),
            ],
            bases=('aec.electoralregion',),
        ),
        migrations.AddField(
            model_name='voterrecord',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aec.ElectoralRegion'),
        ),
        migrations.AddField(
            model_name='partymembership',
            name='person',
            field=models.ForeignKey(help_text='The person who is a party to the relationship', on_delete=django.db.models.deletion.CASCADE, related_name='party_memberships', to='aec.Person'),
        ),
        migrations.AddField(
            model_name='firstpreferencevotes',
            name='person',
            field=models.ForeignKey(help_text='The relation to a person associated with this result.', on_delete=django.db.models.deletion.CASCADE, to='aec.Person'),
        ),
        migrations.AddField(
            model_name='firstpreferencevotes',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='aec.ElectoralRegion'),
        ),
        migrations.AddField(
            model_name='electoralregion',
            name='election',
            field=models.ForeignKey(help_text='The election this electorate is for', on_delete=django.db.models.deletion.CASCADE, related_name='electorates', to='aec.Election'),
        ),
        migrations.AddField(
            model_name='alternatename',
            name='person',
            field=models.ForeignKey(help_text='Issued identifiers', on_delete=django.db.models.deletion.CASCADE, related_name='other_names', to='aec.Person'),
        ),
        migrations.AddField(
            model_name='preferencesflow',
            name='division',
            field=models.ForeignKey(help_text='Division the votes were recorded against.', on_delete=django.db.models.deletion.CASCADE, related_name='flows', to='aec.Division'),
        ),
    ]
